### ISSUE TITLE
[BUG] Backend Down nach PR

### ISSUE THREAD

**Issue by lumaghg** [projekt-fitnessapp/backend#53]
**Was ist passiert:**
Backend ist gekracht
```
App started on  http://localhost:4000
/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:207
                    callback(new error_1.MongoServerError(document));
                             ^

MongoServerError: bad auth : Authentication failed.
    at Connection.onMessage (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:207:30)
    at MessageStream.<anonymous> (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
    at MessageStream._write (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:513:28) {
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  [Symbol(errorLabels)]: Set(1) { 'HandshakeError' }
}
```
**Was sollte passieren:**
Backend sollte ganz normal laufen
**Wie kann der Fehler reproduziert werden:**

**Weitere Anmerkungen:**

**Comment by HaseFlrn** [comment]
DB_URL war broken
